[variables]
NODE_ENV = "DEVELOPMENT"
NIXPACKS_METADATA = "monorepo-api"

[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["pnpm run build:api"]

[start]
cmd = "pnpm start:api" 