[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_20", "bun"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["echo 'No build step needed for Bun TypeScript runtime'"]

[start]
cmd = "bun run src/index.ts" 